# Generated by Django 3.2.4 on 2021-07-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210720_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default='none', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='none', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.product'),
        ),
    ]
